### ISSUE TITLE
Simulate cloud operations

### ISSUE THREAD

**Issue by lucadruda** [lucadruda/iotc-java-device-client#6] opened 2021-01-29 15:06 UTC
is there any method to imitate send command from cloud to device in your code?
There are SendProperty ,SendTelemetry, but there is any method like call "SendCommand" which can imitate cloud send data to device?

And for the "SendProperty ", I have property named "firmwareVersion" in central, but I didn't get any message from your code:

 PropertiesCallback onProps = (IoTCProperty property) -> {
            System.out.println(String.format("Received property '%s' with value: %s", property.getName(),
                    property.getValue().toString()));
            property.ack("Property applied");
        };

I invoked the SendProperty, message can see in "Raw data" of device, but the listener didn't get the any message
what should I do?

_Originally posted by @wuwei3 in https://github.com/lucadruda/iotc-java-device-client/issues/4#issuecomment-769620709_

**Comment by lucadruda** [comment] 2021-01-29 15:11
You are mixing concepts here. This is a device client so there is no way to simulate service client (IoT Central) and imitate commands or properties.
If your property is a writeable one then callback should trigger.
Please pull latest version in your pom.xml and try again.

**Comment by wuwei3** [comment] 2021-01-30 13:39
hi,

 I did what you said for the property, but not worked, see the pic


![1](https://user-images.githubusercontent.com/46955295/106357738-e5d70f00-6342-11eb-96d3-74fea187ff06.png)
I config the property and make it "writable"

![2](https://user-images.githubusercontent.com/46955295/106357751-02734700-6343-11eb-8a60-5d78ffe5795a.png)
the display on page

![3](https://user-images.githubusercontent.com/46955295/106357756-0d2ddc00-6343-11eb-8823-b5d5370f3952.png)
I created one test device to run the code, the "Telemetry" and "propertity" data send to central, 


![5](https://user-images.githubusercontent.com/46955295/106357805-4403f200-6343-11eb-8501-675c5e591a22.png)
but the property listener didn't get any response.


I am sorry, I am the green hand on the IOT central, did I something wrong so that the code doesn't work?

**Comment by lucadruda** [comment] 2021-02-01 08:37
Did you pull latest version (2.1.0)?
I can see you are sending the property correctly and listener is well formed. What do you have in Central page when updating the firmware property from the cloud?
Are you using components in your device definition?

**Comment by wuwei3** [comment] 2021-02-01 09:05
> Did you pull latest version (2.1.0)?
   No, can't build success, it still get the same error, I comment in the closed issue.

> I can see you are sending the property correctly and listener is well formed. What do you have in Central page when updating the firmware property from the cloud?
   I created the "firmwareVersion" property in central page and make it "writable"(you can see for the first page in my comment), the data can show in "Raw Data" tab, but the listener didn't get any message.

> Are you using components in your device definition?
  yes, component, default component both used, but both didn't get any response.

**Comment by wuwei3** [comment] 2021-02-01 09:21
![6](https://user-images.githubusercontent.com/46955295/106438581-a24ee300-64b1-11eb-86dd-a6a520323587.png)

from the page, you could see, I create 2,one for default component, one for component, but both were not work for property listener, the data, can show in the "Raw data" tab

![3](https://user-images.githubusercontent.com/46955295/106438742-daeebc80-64b1-11eb-8a79-b057fb9ad013.png)

**Comment by lucadruda** [comment] 2021-02-01 09:23
Listener only works if you change property from Central, not from device. Your device is already sending the property so there is no reason to listen for the same value

**Comment by wuwei3** [comment] 2021-02-01 11:17
> Listener only works if you change property from Central, not from device. Your device is already sending the property so there is no reason to listen for the same value

OK, I see, 

> Listener only works if you change property from Central

 Could you please tell me how to do this for making the listener work? I mean, is there any page or button, can trigger the property listener works?

**Comment by lucadruda** [comment] 2021-02-01 15:15
You have to provide a form view for your properties.
When you define your device template add a form view from "Views" menu.
![image](https://user-images.githubusercontent.com/2270242/106477435-72e7a880-64a8-11eb-9f01-ae526fe00140.png)

Then select property you'd like to change from cloud side and add the section to template.
![image](https://user-images.githubusercontent.com/2270242/106477603-9d396600-64a8-11eb-95e0-833d3f7e8fef.png)

Remember to publish template at the end.

**Comment by wuwei3** [comment] 2021-02-02 03:00
I did what you told

![1](https://user-images.githubusercontent.com/46955295/106546211-b512f780-6545-11eb-8aca-505b220323f8.png)
the value just in "pending" status

click the "Pending", it shows

![2](https://user-images.githubusercontent.com/46955295/106546244-c3f9aa00-6545-11eb-99a8-9c163bc8bd60.png)


but the listener still got nothing, what else can do to make the status change?

**Comment by lucadruda** [comment] 2021-02-02 08:55
Are you sure using the lastest version? Do commands work?
Paste your code here. Property listener should trigger immediately when device is connected and property changes.

**Comment by wuwei3** [comment] 2021-02-02 09:41
Hi， 

Yes, I am sure I using the latest version

![3](https://user-images.githubusercontent.com/46955295/106581001-56697000-657d-11eb-92f2-13e306034016.png)

Commands works well, strange!


I re-clone the codes, and build success (BTW, the iotc-device-samples cannot build success, because it says can't find the iotc-device-client 2.0.1 version in maven central, but I think it's not big issue)

public class TestSendData {
	
	static final String deviceId = "renxing2";
    static final String scopeId = "0ne00200B86";
    static final String deviceKey = "ytBZSkuCZZV0R8rbjawE7hZvhyBL9v9nT7D7jzsgo/Q=";
    
    //device template->model->view entity
    static String modelID = "dtmi:olcsimulationcentral:testforsensor1bk;1";

    static class MemStorage implements ICentralStorage {

        @Override
        public void persist(Storage storage) {
            System.out.println("New credentials available:");
//            System.out.println(storage.getHubName());
//            System.out.println(storage.getDeviceId());
//            System.out.println(storage.getDeviceKey());
            return;
        }

        @Override
        public Storage retrieve() {
            return new Storage();
        }

    }

	public static void main(String[] args) {
		System.out.println("Welcome to IoTCentral");
        IoTCClient client = new IoTCClient(deviceId, scopeId, IOTC_CONNECT.DEVICE_KEY, deviceKey, new MemStorage());
        client.SetLogging(IOTC_LOGGING.ALL);
        
        PropertiesCallback onProps = (IoTCProperty property) -> {
            System.out.println(String.format("Received property '%s' with value: %s", property.getName(),
                    property.getValue().toString()));
            property.ack("Property applied");
        };

        CommandCallback onCommand = (command) -> {
            System.out.println(String.format("Received command '%s' with value: %s", command.getName(),
                    command.getRequestPayload().toString()));
            return command.reply(IOTC_COMMAND_RESPONSE.SUCCESS, "Command executed");
        };

        client.on(IOTC_EVENTS.Properties, onProps);
        client.on(IOTC_EVENTS.Commands, onCommand);
        
        try {
            client.Connect();
            client.SendProperty(String.format("{\"firmwareVersion\":%d}", 12));

            while (true) {
                System.out.println("Sending telemetry");
                client.SendTelemetry(String.format("{\"temperature\":%,.0f}", 35.78));
                try {
					Thread.sleep(300 * 1000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
            }

        } catch (IoTCentralException ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
	}

}


This is my code, just paste from your code, only change the deviceID and device KEY, the device ID in the code is the test device I am using in central, you can use it as test, no worry

**Comment by lucadruda** [comment] 2021-02-02 09:53
Please also attach capability model (//device template->model->export).
If something is wrong on the SDK side you can try to debug by putting a breakpoint in device client at: https://github.com/lucadruda/iotc-java-device-client/blob/889f406ed937285943f0861a5688028c061d0525/iotc-device-client/src/main/java/com/github/lucadruda/iotc/device/IoTCClient.java#L296

**Comment by wuwei3** [comment] 2021-02-02 09:58
The model below:


[
  {
    "@id": "dtmi:olcsimulationcentral:testsen4471;2",
    "@type": "Interface",
    "contents": [
      {
        "@id": "dtmi:olcsimulationcentral:testsen4471:sendConfigToSensor;1",
        "@type": "Command",
        "commandType": "synchronous",
        "displayName": {
          "en": "send config to sensor"
        },
        "name": "sendConfigToSensor",
        "request": {
          "@type": "CommandPayload",
          "displayName": {
            "en": "period"
          },
          "name": "period",
          "schema": "long"
        },
        "response": {
          "@type": "CommandPayload",
          "displayName": {
            "en": "SUCCESS"
          },
          "name": "SUCCESS",
          "schema": "string"
        }
      },
      {
        "@id": "dtmi:olcsimulationcentral:testsen4471:firmwareVersion;1",
        "@type": "Property",
        "displayName": {
          "en": "firmware version"
        },
        "name": "firmwareVersion",
        "schema": "long",
        "writable": true
      },
      {
        "@id": "dtmi:olcsimulationcentral:testsen4471:testsen4V26q5;2",
        "@type": "Component",
        "displayName": {
          "en": "Component"
        },
        "name": "testsen4V26q5",
        "schema": "dtmi:olcsimulationcentral:testsen4V26q5;1"
      }
    ],
    "displayName": {
      "en": "testsen4"
    },
    "extends": [
      "dtmi:olcsimulationcentral:testsen42oj;1"
    ],
    "@context": [
      "dtmi:iotcentral:context;2",
      "dtmi:dtdl:context;2"
    ]
  },
  {
    "@context": [
      "dtmi:iotcentral:context;2",
      "dtmi:dtdl:context;2"
    ],
    "@id": "dtmi:olcsimulationcentral:testsen42oj;1",
    "@type": "Interface",
    "contents": [
      {
        "@id": "dtmi:olcsimulationcentral:testsen42oj:temperature;1",
        "@type": "Telemetry",
        "displayName": {
          "en": "temperature"
        },
        "name": "temperature",
        "schema": "double"
      },
      {
        "@id": "dtmi:olcsimulationcentral:testsen42oj:humidity;1",
        "@type": "Telemetry",
        "displayName": {
          "en": "humidity"
        },
        "name": "humidity",
        "schema": "double"
      }
    ],
    "displayName": {
      "en": "Interface"
    }
  },
  {
    "@context": [
      "dtmi:iotcentral:context;2",
      "dtmi:dtdl:context;2"
    ],
    "@id": "dtmi:olcsimulationcentral:testsen4V26q5;1",
    "@type": "Interface",
    "contents": [
      {
        "@id": "dtmi:olcsimulationcentral:testsen4V26q5:sendConfig2;1",
        "@type": "Command",
        "commandType": "synchronous",
        "displayName": {
          "en": "send config2"
        },
        "name": "sendConfig2",
        "request": {
          "@type": "CommandPayload",
          "displayName": {
            "en": "per"
          },
          "name": "per",
          "schema": "long"
        },
        "response": {
          "@type": "CommandPayload",
          "displayName": {
            "en": "SUCCESS"
          },
          "name": "SUCCESS",
          "schema": "string"
        }
      }
    ],
    "displayName": {
      "en": "Component"
    }
  }
]

**Comment by lucadruda** [comment] 2021-02-02 10:27
I played your code with that model and property listener works good for me.
Double check you don't have old instances running.
Also check your modelId. Id in your json model it looks different from the code above. It should be "dtmi:olcsimulationcentral:testsen4471;2"

**Comment by wuwei3** [comment] 2021-02-02 10:32
Ok, modelID I don't use it.

I didn't have any old instance running, very strange, whatever, many thanks for your help.

**Comment by wuwei3** [comment] 2021-02-03 02:29
I know why, the root problem is I didn't sent data with JSON, in your code (IoTCClient listenToProperties()):

JsonObject payloadObject = (JsonObject) new JsonParser().parse(property.getValue().toString());

if the receive data is not JSON, this line will get exception


![1](https://user-images.githubusercontent.com/46955295/106689038-45b30b80-660a-11eb-96e4-377639a6511c.png)

from the pic, I just put {"firmwareVersion":4}, but the receive data is only "4.0", not the JSON, so it cannot exec the below codes.

Very Strange, I did what you did in your code, I don't know why it cannot to be JSON

Another thing is in the pic, "sendConfigToSensor" is command type, I just 
client.on(IOTC_EVENTS.Properties, onProps);

I don't know why the command also be responsed,but I didn't do any command operation.

**Comment by lucadruda** [comment] 2021-02-10 14:02
It's not clear to me what you are trying to do.
IoTCentral sends properties in JSON format so your device code should be able to receive it in the right way.
Property message in the format {"ac":...,"ad":...} is a response message client sends back to ack new property value. Why are you receiving this back on client side?
Looks like your scenario is wrong in some parts

**Comment by wuwei3** [comment] 2021-02-18 04:54
Hi

I always get this error:

com.github.lucadruda.iotc.device.exceptions.IoTCentralException: Registration error, bailing out
	at com.github.lucadruda.iotc.device.DeviceProvision._internalRegister(DeviceProvision.java:138)
	at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:99)
	at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:73)
	at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:159)
	at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:153)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.utils.DeviceConnUtils.isOpen(DeviceConnUtils.java:60)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.reOpenConnection(PushDataThread.java:128)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.run(PushDataThread.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


I think, my network was ok, how this caused?

**Comment by wuwei3** [comment] 2021-02-18 04:57
Another exception info:

Caused by: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceConnectionException: Exception opening connection
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:175)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.authenticateWithProvisioningService(ContractAPIMqtt.java:228)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithSasToken(RegisterTask.java:202)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithDPS(RegisterTask.java:319)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:341)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
Caused by: java.io.IOException: Unable to subscribe on topic : $dps/registrations/res/#
	at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:236)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:170)
	... 11 more
Caused by: Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
	at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:232)
	... 12 more
com.github.lucadruda.iotc.device.exceptions.IoTCentralException: Registration error, bailing out
	at com.github.lucadruda.iotc.device.DeviceProvision._internalRegister(DeviceProvision.java:138)
	at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:99)
	at com.github.lucadruda.iotc.device.DeviceProvision.register(DeviceProvision.java:73)
	at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:159)
	at com.github.lucadruda.iotc.device.IoTCClient.Connect(IoTCClient.java:153)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.utils.DeviceConnUtils.isOpen(DeviceConnUtils.java:60)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.reOpenConnection(PushDataThread.java:128)
	at com.orangelabs.iot.azure.central.IOTAzureCentralTest.testsend.pushdata.PushDataThread.run(PushDataThread.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lucadruda** [comment] 2021-02-18 09:50
Please open separate issues if topics are not related.
Anyway, that looks like an error on DPS, either you can't reach the global url, your credentials are not valid or your device registration in the hub got corrupted. Try to change device Id and provision a different one to exclude corruption.

**Comment by wuwei3** [comment] 2021-02-19 04:16
ok, I submitted another issue, you could close this one, many thanks.

**Closed as completed** 2021-03-10 08:34 UTC
